### ISSUE TITLE
Implement Logger

### ISSUE THREAD

**Issue by Pedro12909** [Pedro12909/RexCord#14]

**Comment by Pedro12909** [comment]
Discord4J: ERROR INITIALIZING LOGGER!
Discord4J: No SLF4J implementation found, reverting to the internal implementation (sx.blah.discord.Discord4J$Discord4JLogger)
Discord4J: It is *highly* recommended to use a fully featured implementation like logback!

**Comment by freitzzz** [comment]
Found the error. Discord4J searches for the following class "org.slf4j.impl.StaticLoggerBinder" which is not found in maven sl4j dependencies.

Possible fixes:
- Search for newer SL4J versions (currently installed 1.7.2.4)
- Search for other SL4J dependencies that replace StaticLoggerBinder implementation

**Comment by freitzzz** [comment]
Hello people from all over the world! 😊
You are probably seeing this because you are participating on Hacktoberfest, and want to contribute to open source projects since you want to take on new challenges or you just want win a free tshirt 😅 (But that's good!)

#############
***If you are new to RexCord I advise you reading [README.MD](README.md) and [CONTRIBUTING.MD](CONTRIBUTING.md) as well as the RexCord [wiki](https://github.com/Pedro12909/RexCord/wiki)***
#############

We are having issues with this one, basically RexCord is built to have a live action logging system so that the bot admin can know every action that occured on the bot. In this case, RexCord for default tries to use SL4J logging system, but is not found in the maven dependencies, even though that SL4J dependency is added on maven.
The bot still runs without a logger, but it would be very cool if we fix this problem, because no one likes to run things that give warnings on startup! 😅
