### ISSUE TITLE
Music Player - play command needs to be executed twice to queue song

### ISSUE THREAD

**Issue by Pedro12909** [Pedro12909/RexCord#65]
If a user tries to queue a song, RexCord shows an error and doesn't queue the requested song. However, if the user tries to queue the same song again, it will queue correctly and play.

**Comment by EthanTheMaster** [comment]
Yeah, I experienced this bug too. This error occurs when the user tries to queue up a youtube link. For some reason, the song will queue without a problem if the youtube to mp3 API has the mp3 in cache which occurs when the youtube link has been converted within what seems to be a 24 hour period(this is why no error will occur when the same song is queued again as the song would be in cache after the first queue up). Also, no problem will occur if the queued song directly links to the generated audio file link. In the search for a solution, I noticed that the error would occur because RexCord would make a connection for the mp3 only to be redirected as the server would throw an HTTP 307 error. When checking the redirection, I noticed that the redirection would lead to an ad page which could be due to the youtube to mp3 API. Because the HTTP connection is redirected to an ad page, there is no audio file to extract, and thus RexCord throws an error. The reason queuing works the second time around also seems to lie in the fact that no redirection is done after the first queue.
